# 5. Data Preprocessing

Data preprocessing is a crucial step in the machine learning pipeline. Raw data is often messy, incomplete, and inconsistent. Preprocessing helps clean, transform, and prepare data for modeling, which directly impacts model performance.


In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder, OneHotEncoder, PolynomialFeatures

print ('Libraries imported successfully!')


Libraries imported successfully!


## 5.1 Why Preprocessing?

Real-world data is never clean. It contains missing values, outliers, inconsistent formats, and features on different scales. Preprocessing addresses these issues so that machine learning algorithms can work effectively.

**Key reasons to preprocess data:**
- Algorithms like SVM, KNN, and PCA are sensitive to feature scales
- Most models cannot handle missing values natively
- Categorical data must be converted to numerical form
- Feature engineering can improve model accuracy

> **"Garbage in, garbage out"** — preprocessing ensures quality input.


#### 5.1.1 Importance of Scaling

Consider two features: **Age** (0–100) and **Salary** (0–200,000). Algorithms using distance measures (KNN, K-Means, SVM) will be dominated by Salary simply because of its larger magnitude. Scaling fixes this.

sklearn.**StandardScaler**(*copy=True, with_mean=True, with_std=True*)


In [2]:
# Demonstrate why scaling matters
data = np.array([[25, 50000], [30, 60000], [35, 75000], [40, 80000], [45, 100000]])
print ('Original data:\n%s' % str(data))
print ('\nFeature 1 (Age) - mean: %.1f, std: %.1f' % (np.mean(data[:, 0]), np.std(data[:, 0])))
print ('Feature 2 (Salary) - mean: %.1f, std: %.1f' % (np.mean(data[:, 1]), np.std(data[:, 1])))
print ('\nSalary dominates distance calculations!')


Original data:
[[   25 50000]
 [   30 60000]
 [   35 75000]
 [   40 80000]
 [   45 100000]]

Feature 1 (Age) - mean: 35.0, std: 7.1
Feature 2 (Salary) - mean: 73000.0, std: 17888.5

Salary dominates distance calculations!


<hr>

## 5.2 Handling Missing Values

Missing data is a common issue. Pandas represents missing values as `NaN` (Not a Number). We can detect, drop, or fill them.


#### 5.2.1 Creating DataFrame with NaN

We can create missing values using `np.nan` in a DataFrame.

pd.**DataFrame**(*data*) with **numpy.nan** entries


In [3]:
# Create a DataFrame with missing values
df = pd.DataFrame({
    'A': [1, 2, np.nan, 4, 5],
    'B': [np.nan, 2, 3, np.nan, 5],
    'C': [1, 2, 3, 4, 5],
    'D': [np.nan, np.nan, np.nan, np.nan, 5]
})
print ('DataFrame with missing values:\n%s' % str(df))


DataFrame with missing values:
     A    B  C    D
0  1.0  NaN  1  NaN
1  2.0  2.0  2  NaN
2  NaN  3.0  3  NaN
3  4.0  NaN  4  NaN
4  5.0  5.0  5  5.0


#### 5.2.2 Detecting and Handling Missing Values

Use `isnull()` to detect, `dropna()` to remove, and `fillna()` to replace missing values.

pd.DataFrame.**isnull**() → pd.DataFrame.**dropna**(*axis=0*) → pd.DataFrame.**fillna**(*value*)


In [4]:
# Detecting missing values
print ('isnull() - detecting NaN:\n%s' % str(df.isnull()))

print ('\nDrop rows with any NaN:\n%s' % str(df.dropna()))

print ('\nFill all NaN with 0:\n%s' % str(df.fillna(0)))

print ('\nFill NaN with column mean:\n%s' % str(df.fillna(df.mean())))


isnull() - detecting NaN:
       A      B      C      D
0  False   True  False   True
1  False  False  False   True
2   True  False  False   True
3  False   True  False   True
4  False  False  False  False

Drop rows with any NaN:
     A    B  C    D
4  5.0  5.0  5  5.0

Fill all NaN with 0:
     A    B  C    D
0  1.0  0.0  1  0.0
1  2.0  2.0  2  0.0
2  0.0  3.0  3  0.0
3  4.0  0.0  4  0.0
4  5.0  5.0  5  5.0

Fill NaN with column mean:
     A    B  C    D
0  1.0  3.0  1  5.0
1  2.0  2.0  2  5.0
2  3.0  3.0  3  5.0
3  4.0  3.0  4  5.0
4  5.0  5.0  5  5.0


<hr>

## 5.3 Feature Scaling

Feature scaling standardizes the range of features. Two common methods:

- **Standardization**: $$z = \frac{x - \mu}{\sigma}$$ results in zero mean and unit variance
- **Min-Max Scaling**: $$x_{norm} = \frac{x - x_{min}}{x_{max} - x_{min}}$$ scales to [0, 1]


#### 5.3.1 StandardScaler

StandardScaler removes the mean and scales to unit variance.

sklearn.preprocessing.**StandardScaler**(*copy=True, with_mean=True, with_std=True*)

`.fit()` computes mean & std, `.transform()` applies scaling, `.fit_transform()` does both.


In [5]:
# StandardScaler on synthetic data
X = np.array([[1, 2], [2, 3], [3, 4], [4, 5], [5, 6]], dtype=float)
print ('Original data:\n%s' % str(X))
print ('\nMean before: %s' % str(np.mean(X, axis=0)))
print ('Std before: %s' % str(np.std(X, axis=0)))

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

print ('\nAfter StandardScaler:\n%s' % str(X_scaled))
print ('\nMean after: %s' % str(np.mean(X_scaled, axis=0)))
print ('Std after: %s' % str(np.std(X_scaled, axis=0)))


Original data:
[[1. 2.]
 [2. 3.]
 [3. 4.]
 [4. 5.]
 [5. 6.]]

Mean before: [3. 4.]
Std before: [1.41421356 1.41421356]

After StandardScaler:
[[-1.41421356 -1.41421356]
 [-0.70710678 -0.70710678]
 [ 0.          0.        ]
 [ 0.70710678  0.70710678]
 [ 1.41421356  1.41421356]]

Mean after: [0. 0.]
Std after: [1. 1.]


#### 5.3.2 MinMaxScaler

MinMaxScaler scales each feature to a given range (default [0, 1]).

sklearn.preprocessing.**MinMaxScaler**(*feature_range=(0, 1), copy=True*)


In [6]:
# MinMaxScaler on synthetic data
X = np.array([[1, 2], [2, 3], [3, 4], [4, 5], [5, 6]], dtype=float)
print ('Original data:\n%s' % str(X))
print ('\nMin before: %s' % str(np.min(X, axis=0)))
print ('Max before: %s' % str(np.max(X, axis=0)))

mms = MinMaxScaler()
X_mms = mms.fit_transform(X)

print ('\nAfter MinMaxScaler:\n%s' % str(X_mms))
print ('\nMin after: %s' % str(np.min(X_mms, axis=0)))
print ('Max after: %s' % str(np.max(X_mms, axis=0)))


Original data:
[[1. 2.]
 [2. 3.]
 [3. 4.]
 [4. 5.]
 [5. 6.]]

Min before: [1. 2.]
Max before: [5. 6.]

After MinMaxScaler:
[[0.   0.  ]
 [0.25 0.25]
 [0.5  0.5 ]
 [0.75 0.75]
 [1.   1.  ]]

Min after: [0. 0.]
Max after: [1. 1.]


<hr>

## 5.4 Encoding Categorical Variables

Machine learning algorithms require numerical input. Encoding converts categorical data into numbers.

- **Label Encoding**: assigns a unique integer to each category
- **One-Hot Encoding**: creates binary columns for each category


#### 5.4.1 LabelEncoder

sklearn.preprocessing.**LabelEncoder**()

Transforms `['cat', 'dog', 'bird']` → `[0, 1, 2]`.


In [7]:
# LabelEncoder demo
animals = np.array(['cat', 'dog', 'bird', 'dog', 'cat'])
print ('Original: %s' % str(animals))

le = LabelEncoder()
encoded = le.fit_transform(animals)

print ('Encoded:  %s' % str(encoded))
print ('Classes:  %s' % str(le.classes_))
print ('Inverse:  %s' % str(le.inverse_transform(encoded)))


Original: ['cat' 'dog' 'bird' 'dog' 'cat']
Encoded:  [0 1 2 1 0]
Classes:  ['bird' 'cat' 'dog']
Inverse:  ['cat' 'dog' 'bird' 'dog' 'cat']


#### 5.4.2 OneHotEncoder

sklearn.preprocessing.**OneHotEncoder**(*categories='auto', sparse=False*)

Creates a binary column for each category. Avoids implying ordinal relationships.


In [8]:
# OneHotEncoder demo
colors = np.array([['red'], ['blue'], ['green'], ['blue'], ['red']])
print ('Original:\n%s' % str(colors))

ohe = OneHotEncoder(sparse=False)
encoded = ohe.fit_transform(colors)

print ('\nOne-hot encoded:\n%s' % str(encoded))
print ('\nCategories: %s' % str(ohe.categories_))


Original:
[['red']
 ['blue']
 ['green']
 ['blue']
 ['red']]

One-hot encoded:
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]

Categories: [array(['blue', 'green', 'red'], dtype='<U5')]


<hr>

## 5.5 Polynomial Features

PolynomialFeatures generates interaction and polynomial features from existing ones.

$$\text{For } [x_0, x_1] \text{ with degree=2: } [1, x_0, x_1, x_0^2, x_0 x_1, x_1^2]$$

sklearn.preprocessing.**PolynomialFeatures**(*degree=2, interaction_only=False, include_bias=True*)


In [9]:
# PolynomialFeatures demo
X = np.array([[1, 2], [3, 4]])
print ('Original features:\n%s' % str(X))

poly = PolynomialFeatures(degree=2)
X_poly = poly.fit_transform(X)

print ('\nPolynomial features (degree=2):\n%s' % str(X_poly))
print ('\nFeature names: %s' % str(poly.get_feature_names()))


Original features:
[[1 2]
 [3 4]]

Polynomial features (degree=2):
[[ 1.  1.  2.  1.  2.  4.]
 [ 1.  3.  4.  9. 12. 16.]]

Feature names: ['1', 'x0', 'x1', 'x0^2', 'x0 x1', 'x1^2']


<hr>

## 5.6 train_test_split

Splits data into training and testing sets to evaluate model performance on unseen data.

sklearn.model_selection.**train_test_split**(*arrays, test_size=0.25, random_state=None*)

Typical splits: 70-30 or 80-20 for train-test.


In [10]:
# train_test_split on Iris dataset
from sklearn.datasets import load_iris

iris = load_iris()
X, y = iris.data, iris.target

print ('X shape: %s, y shape: %s' % (str(X.shape), str(y.shape)))

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print ('X_train shape: %s' % str(X_train.shape))
print ('X_test shape:  %s' % str(X_test.shape))
print ('y_train shape: %s' % str(y_train.shape))
print ('y_test shape:  %s' % str(y_test.shape))
print ('\nTrain size: %d (%.0f%%), Test size: %d (%.0f%%)' % (len(X_train), 80, len(X_test), 20))


X shape: (150, 4), y shape: (150,)
X_train shape: (120, 4)
X_test shape:  (30, 4)
y_train shape: (120,)
y_test shape:  (30,)

Train size: 120 (80%), Test size: 30 (20%)


<hr>

## 5.7 Assignment

Complete the following exercises to practice data preprocessing.

1. Create a DataFrame with 10 rows and 3 columns containing at least 3 missing values. Use `fillna()` to replace them with the column median.
2. Apply **StandardScaler** to the Iris dataset and verify that the scaled data has zero mean and unit variance.
3. Apply **MinMaxScaler** to the Iris dataset and verify the range is [0, 1].
4. Create a categorical array with 5 unique values and apply **LabelEncoder**. Verify inverse transform works.
5. Generate polynomial features of degree 3 from a 2-feature array. How many features do you get?
6. Split the Iris dataset into 70-30 train-test split. Print all four shapes.

**Bonus**: Chain StandardScaler → PolynomialFeatures → train_test_split on the Iris dataset.


In [11]:
# ============================================
# 5.7 Assignment — Data Preprocessing
# ============================================
# Complete each exercise below

import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder, OneHotEncoder, PolynomialFeatures
from sklearn.datasets import load_iris

# 1. Missing values - fill with median
# df_miss = pd.DataFrame(...)
# print(df_miss.fillna(df_miss.median()))

# 2. StandardScaler on Iris
# iris = load_iris()
# scaler = StandardScaler()
# X_scaled = scaler.fit_transform(iris.data)
# print('Mean:', np.mean(X_scaled, axis=0))
# print('Std:', np.std(X_scaled, axis=0))

# 3. MinMaxScaler on Iris
# mms = MinMaxScaler()
# X_mms = mms.fit_transform(iris.data)
# print('Min:', np.min(X_mms, axis=0))
# print('Max:', np.max(X_mms, axis=0))

# 4. LabelEncoder with 5 categories
# cats = np.array(['a', 'b', 'c', 'd', 'e', 'a', 'c', 'e'])
# le = LabelEncoder()
# enc = le.fit_transform(cats)
# print('Encoded:', enc)
# print('Inverse:', le.inverse_transform(enc))

# 5. PolynomialFeatures degree 3, 2 features
# X = np.array([[1, 2], [3, 4]])
# poly = PolynomialFeatures(degree=3)
# X_poly = poly.fit_transform(X)
# print('Shape:', X_poly.shape, 'Features:', poly.get_feature_names())

# 6. 70-30 split on Iris
# X_train, X_test, y_train, y_test = train_test_split(
#     iris.data, iris.target, test_size=0.3, random_state=42)
# print('Train:', X_train.shape, y_train.shape)
# print('Test:', X_test.shape, y_test.shape)

print ('\nAll exercises are ready — replace comments with code!')



All exercises are ready — replace comments with code!
