# Introduction to NumPy

NumPy is the foundational library for numerical computing in Python. It provides the **ndarray** object which is way faster and more memory-efficient than native Python lists. Let's dive right in!


In [1]:
%matplotlib inline
import numpy as np

print("NumPy imported successfully!")


NumPy imported successfully!


---


## 1.1 Initialization of 1D Array

Creating one-dimensional arrays is the first thing you'll do in NumPy. Let's look at a few ways.


### From a Python List

Use `numpy.array(**object**, dtype=None)` to convert any sequence into an ndarray.


In [2]:
v = np.array([1, 4, 9, 3, 2])
print("v = %s" % str(v))


v = [1 4 9 3 2]


### Using `numpy.arange()`

Like Python's `range()` but returns an ndarray.


In [3]:
a1 = np.arange(5)
a2 = np.arange(2, 5)
a3 = np.arange(0, -10, -2)

print("np.arange(5)      = %s" % str(a1))
print("np.arange(2,5)    = %s" % str(a2))
print("np.arange(0,-10,-2) = %s" % str(a3))


np.arange(5)      = [0 1 2 3 4]
np.arange(2,5)    = [2 3 4]
np.arange(0,-10,-2) = [ 0 -2 -4 -6 -8]


### Checking `dtype` and `shape`

Every ndarray has a **dtype** (data type) and a **shape** (tuple of dimensions).


In [4]:
v = np.array([1, 4, 9, 3, 2])
print("Value  = %s" % str(v))
print("dtype  = %s" % str(v.dtype))
print("shape  = %s" % str(v.shape))


Value  = [1 4 9 3 2]
dtype  = int64
shape  = (5,)


<hr>


## 1.2 Initialization of 2D Array

Moving from 1D to 2D is where things get interesting!


### From a List of Lists


In [5]:
mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("mat = \n%s" % str(mat))


mat = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### `zeros()` and `ones()`

Create arrays pre-filled with 0 or 1 — super handy for initialization.


In [6]:
z = np.zeros((3, 3))
o = np.ones((2, 4))

print("np.zeros((3,3)) = \n%s" % str(z))
print("\nnp.ones((2,4)) = \n%s" % str(o))


np.zeros((3,3)) = 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

np.ones((2,4)) = 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### Random Arrays

NumPy has a whole submodule `numpy.random` for generating random data.


In [7]:
print("np.random.random((2,3)) = \n%s" % str(np.random.random((2,3))))
print("\nnp.random.randint(0,10,(3,3)) = \n%s" % str(np.random.randint(0,10,(3,3))))
print("\nnp.random.randn(2,4) = \n%s" % str(np.random.randn(2,4)))


np.random.random((2,3)) = 
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]]

np.random.randint(0,10,(3,3)) = 
[[4 7 0]
 [1 8 9]
 [2 5 3]]

np.random.randn(2,4) = 
[[ 0.59390198 -1.02855188  0.41371724  1.04471838]
 [-0.72400102 -0.91152766 -0.06183921  0.21485299]]


### Shape and Flatten


In [8]:
mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Shape is %s\n" % str(mat.shape))
print("Original:\n%s\n" % str(mat))
print("Flattened:\n%s" % str(mat.flatten()))

# Reshape back
flat = mat.flatten()
print("\nReshaped to (1,9):\n%s" % str(flat.reshape(1,9)))


Shape is (3, 3)

Original:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Flattened:
[1 2 3 4 5 6 7 8 9]

Reshaped to (1,9):
[[1 2 3 4 5 6 7 8 9]]


<hr>


## 1.3 Slicing and Indexing

Slicing in NumPy works just like Python lists but extended to multiple dimensions. This is where the real power comes in.


In [9]:
vec = np.arange(10)
print("vec = %s" % str(vec))

print("\nvec[2:5]   = %s" % str(vec[2:5]))
print("vec[:-3]   = %s" % str(vec[:-3]))
print("vec[::2]   = %s" % str(vec[::2]))
print("vec[::-1]  = %s" % str(vec[::-1]))


vec = [0 1 2 3 4 5 6 7 8 9]

vec[2:5]   = [2 3 4]
vec[:-3]   = [0 1 2 3 4 5 6]
vec[::2]   = [0 2 4 6 8]
vec[::-1]  = [9 8 7 6 5 4 3 2 1 0]


### Fancy Indexing with Index Lists

You can pass a list of indices to pull out specific elements.


In [10]:
vec = np.arange(10)
print("vec = %s" % str(vec))
print("vec[[0, 1, 5]] = %s" % str(vec[[0, 1, 5]]))
print("vec[[3, 7, 2, 9]] = %s" % str(vec[[3, 7, 2, 9]]))


vec = [0 1 2 3 4 5 6 7 8 9]
vec[[0, 1, 5]] = [0 1 5]
vec[[3, 7, 2, 9]] = [3 7 2 9]


### Submatrix Slicing & Splitting


In [11]:
mat = np.arange(12).reshape(3, 4)
print("mat = \n%s" % str(mat))

print("\nmat[0:2, -2:] = \n%s" % str(mat[0:2, -2:]))


mat = 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

mat[0:2, -2:] = 
[[2 3]
 [6 7]]


#### `hsplit` and `vsplit`

Split arrays horizontally or vertically.


In [12]:
mat = np.arange(12).reshape(3, 4)
print("Original:\n%s" % str(mat))

left, right = np.hsplit(mat, 2)
print("\nhsplit left:\n%s" % str(left))
print("\nhsplit right:\n%s" % str(right))

top, bottom = np.vsplit(mat, 3)
print("\nvsplit top:\n%s" % str(top))


Original:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

hsplit left:
[[0 1]
 [4 5]
 [8 9]]

hsplit right:
[[ 2  3]
 [ 6  7]
 [10 11]]

vsplit top:
[[0 1 2 3]]


<hr>


## 1.4 Pass By Reference

Important gotcha! NumPy slices are **views**, not copies. Modifying a slice modifies the original array (and vice versa).


### Memory Location — Same Object


In [13]:
v = np.array([1, 2, 3, 4, 5])
w = v[:3]  # w is a view of v

print("v = %s" % str(v))
print("w = %s" % str(w))

# Modify w
w[0] = 999
print("\nAfter w[0] = 999:")
print("v = %s" % str(v))
print("w = %s" % str(w))
print("\nSame memory? v.base is w.base: %s" % str(v.base is w.base))
print("v.base is None:", v.base is None)
print("w.base is v:", w.base is v)


v = [1 2 3 4 5]
w = [1 2 3]

After w[0] = 999:
v = [999   2   3   4   5]
w = [999   2   3]

Same memory? v.base is w.base: False
v.base is None: True
w.base is v: True


### Making a Proper Copy with `.copy()`

Use `.copy()` when you want an independent array.


In [14]:
v = np.array([1, 2, 3, 4, 5])
c = v.copy()  # independent copy

print("v = %s" % str(v))
print("c = %s" % str(c))

c[0] = 777
print("\nAfter c[0] = 777:")
print("v = %s" % str(v))
print("c = %s" % str(c))
print("\nAre they independent?", c.base is None and not np.shares_memory(v, c))


v = [1 2 3 4 5]
c = [1 2 3 4 5]

After c[0] = 777:
v = [1 2 3 4 5]
c = [777   2   3   4   5]

Are they independent? True


<hr>


## 1.5 Broadcast Operation

Broadcasting lets NumPy work with arrays of different shapes during arithmetic operations. Read the docs for the full rules, but here's a taste.


### Scalar + Array, Vector + Matrix


In [15]:
mat = np.arange(1, 13).reshape(3, 4)
v = np.array([10, 20, 30, 40])

print("mat = \n%s" % str(mat))
print("\nv = %s" % str(v))

print("\nmat + 1 = \n%s" % str(mat + 1))
print("\nmat + v = \n%s" % str(mat + v))
print("\nmat * 2 = \n%s" % str(mat * 2))
print("\nmat * v = \n%s" % str(mat * v))


mat = 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

v = [10 20 30 40]

mat + 1 = 
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]

mat + v = 
[[11 22 33 44]
 [15 26 37 48]
 [19 30 41 52]]

mat * 2 = 
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

mat * v = 
[[ 10  40  90 160]
 [ 50 120 210 320]
 [ 90 200 330 480]]


<hr>


## 1.6 Matrix Operations

NumPy provides linear-algebra operations through `np.dot()` and the `@` operator.


### Dot Product

- Vector-vector: scalar
- Matrix-vector: vector
- Matrix-matrix: matrix


In [16]:
# Vector-vector dot product
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("a = %s" % str(a))
print("b = %s" % str(b))
print("a . b (dot) = %d" % np.dot(a, b))
print("a @ b      = %d" % (a @ b))

print()

# Matrix-vector
M = np.array([[1, 2], [3, 4], [5, 6]])
v = np.array([7, 8])
print("M = \n%s" % str(M))
print("v = %s" % str(v))
print("M @ v = %s" % str(M @ v))

print()

# Matrix-matrix
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("A @ B = \n%s" % str(A @ B))


a = [1 2 3]
b = [4 5 6]
a . b (dot) = 32
a @ b      = 32

M = 
[[1 2]
 [3 4]
 [5 6]]
v = [7 8]
M @ v = [23 53 83]

A @ B = 
[[19 22]
 [43 50]]


### Outer Product

The outer product of two vectors produces a matrix.


In [17]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("a = %s" % str(a))
print("b = %s" % str(b))
print("\nnp.outer(a, b) = \n%s" % str(np.outer(a, b)))


a = [1 2 3]
b = [4 5 6]

np.outer(a, b) = 
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


<hr>


## 1.7 Statistical Functions

NumPy has all the stats you need — `mean`, `var`, `sum`, `max`, `min`, `percentile`.


### Basic Statistics


In [18]:
data = np.array([2, 4, 6, 8, 10, 12, 14, 16])

print("data = %s" % str(data))
print("mean  = %.1f" % np.mean(data))
print("var   = %.1f" % np.var(data))
print("sum   = %d" % np.sum(data))
print("max   = %d" % np.max(data))
print("min   = %d" % np.min(data))
print("perc 75th = %.1f" % np.percentile(data, 75))


data = [ 2  4  6  8 10 12 14 16]
mean  = 9.0
var   = 21.0
sum   = 72
max   = 16
min   = 2
perc 75th = 13.0


### Statistical Functions with `axis`

The `axis` parameter controls which dimension you operate along.
- **axis=0**: operate along rows (collapse rows into column result)
- **axis=1**: operate along columns (collapse columns into row result)


In [19]:
mat = np.arange(1, 13).reshape(3, 4)
print("mat = \n%s" % str(mat))

print("\nmean (all)   = %.1f" % np.mean(mat))
print("mean axis=0 = %s" % str(np.mean(mat, axis=0)))
print("mean axis=1 = %s" % str(np.mean(mat, axis=1)))

print("\nsum axis=0   = %s" % str(np.sum(mat, axis=0)))
print("sum axis=1   = %s" % str(np.sum(mat, axis=1)))

print("\nmax axis=0   = %s" % str(np.max(mat, axis=0)))
print("max axis=1   = %s" % str(np.max(mat, axis=1)))


mat = 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

mean (all)   = 6.5
mean axis=0 = [5. 6. 7. 8.]
mean axis=1 = [2.5 6.5 10.5]

sum axis=0   = [15 18 21 24]
sum axis=1   = [10 26 42]

max axis=0   = [ 9 10 11 12]
max axis=1   = [ 4  8 12]


<hr>


## 1.8 Miscellaneous Functions

A couple of handy utilities you will use all the time.


### `squeeze()` — Remove singleton dimensions


In [20]:
arr = np.array([[[1], [2], [3]]])  # shape (1, 3, 1)
print("Original shape: %s" % str(arr.shape))
print("Original:\n%s" % str(arr))

sq = np.squeeze(arr)
print("\nSqueezed shape: %s" % str(sq.shape))
print("Squeezed:\n%s" % str(sq))

# Also works with specific axis
sq0 = np.squeeze(arr, axis=0)
print("\nSqueeze axis=0 only, shape: %s" % str(sq0.shape))


Original shape: (1, 3, 1)
Original:
[[[1]
  [2]
  [3]]]

Squeezed shape: (3,)
Squeezed:
[1 2 3]

Squeeze axis=0 only, shape: (3, 1)


### `transpose()` / `.T` — Flip dimensions


In [21]:
mat = np.array([[1, 2, 3], [4, 5, 6]])
print("Original shape: %s" % str(mat.shape))
print("Original:\n%s" % str(mat))

print("\nTranspose shape: %s" % str(mat.T.shape))
print("Transpose:\n%s" % str(mat.T))

# 3D transpose
arr3d = np.arange(12).reshape(2, 3, 2)
print("\n3D original shape: %s" % str(arr3d.shape))
print("3D transposed shape: %s" % str(np.transpose(arr3d, (2, 1, 0)).shape))


Original shape: (2, 3)
Original:
[[1 2 3]
 [4 5 6]]

Transpose shape: (3, 2)
Transpose:
[[1 4]
 [2 5]
 [3 6]]

3D original shape: (2, 3, 2)
3D transposed shape: (2, 3, 2)


<hr>


### *Class Assignment*

Try these exercises on your own to reinforce the concepts.


In [22]:
# Exercise 1: Create a 1D array from [10, 20, 30, 40, 50]

# Exercise 2: Use np.arange to create [0 1 2 3 4 5 6 7 8 9]

# Exercise 3: Create [5 6 7 8 9] using np.arange

# Exercise 4: Create a 3x3 matrix of zeros

# Exercise 5: Create a 2x5 matrix of ones

# Exercise 6: Create a 4x4 identity matrix (look up np.eye)

# Exercise 7: Create a random 3x3 matrix

# Exercise 8: Extract the first 3 elements of np.arange(10)

# Exercise 9: Extract elements at even indices of [0..9]

# Exercise 10: Reverse [0..9]

# Exercise 11: From a 4x4 matrix, extract the 2x2 bottom-right corner

# Exercise 12: Show that slicing creates a view (not a copy)

# Exercise 13: Create a 3x3 matrix of 1s, add 5 to every element

# Exercise 14: Compute dot product of [1,2,3] and [4,5,6]

# Exercise 15: Compute mean of [1..10] along axis=0 (as 2D row vector)

# Exercise 16: Flatten a 3x4 matrix and reshape back

# Exercise 17: Squeeze an array of shape (1,5,1) to (5,)

# Exercise 18: Transpose a 2x3 matrix

print("All exercises are set up — replace comments with code!")


All exercises are set up — replace comments with code!


# Chapter 1 Assignment

Complete all 18 exercises below. Write working NumPy code for each one.

| # | Task |
|---|------|
| 1 | Create 1D array `[10, 20, 30, 40, 50]` |
| 2 | Use `np.arange` to make `[0 1 2 3 4 5 6 7 8 9]` |
| 3 | Use `np.arange` to make `[5 6 7 8 9]` |
| 4 | `np.zeros((3,3))` |
| 5 | `np.ones((2,5))` |
| 6 | `np.eye(4)` |
| 7 | `np.random.randn(3,3)` |
| 8 | Slice first 3 elements of `[0..9]` |
| 9 | Slice even-index elements of `[0..9]` |
| 10 | Reverse `[0..9]` |
| 11 | Extract bottom-right 2x2 from 4x4 matrix |
| 12 | Prove slicing is a view (modify slice, check original) |
| 13 | Add 5 to every element of `np.ones((3,3))` |
| 14 | `np.dot([1,2,3], [4,5,6])` |
| 15 | `np.mean` of `[1..10]` as 2D row vector |
| 16 | Flatten 3x4 to 1D, then reshape back |
| 17 | `np.squeeze` shape `(1,5,1)` |
| 18 | `.T` transpose of 2x3 matrix |


In [23]:
# ============================================
# Chapter 1 Assignment — NumPy Fundamentals
# ============================================
# Uncomment and complete each exercise

import numpy as np

# 1. Create 1D array [10, 20, 30, 40, 50]
# arr1 = np.array([10, 20, 30, 40, 50])
# print("1:", arr1)

# 2. np.arange to make [0 1 2 3 4 5 6 7 8 9]
# arr2 = np.arange(10)
# print("2:", arr2)

# 3. np.arange to make [5 6 7 8 9]
# arr3 = np.arange(5, 10)
# print("3:", arr3)

# 4. zeros((3,3))
# arr4 = np.zeros((3, 3))
# print("4:\n", arr4)

# 5. ones((2,5))
# arr5 = np.ones((2, 5))
# print("5:\n", arr5)

# 6. eye(4)
# arr6 = np.eye(4)
# print("6:\n", arr6)

# 7. random.randn(3,3)
# arr7 = np.random.randn(3, 3)
# print("7:\n", arr7)

# 8. Slice first 3 of [0..9]
# vec = np.arange(10)
# arr8 = vec[:3]
# print("8:", arr8)

# 9. Even indices
# arr9 = vec[::2]
# print("9:", arr9)

# 10. Reverse
# arr10 = vec[::-1]
# print("10:", arr10)

# 11. Bottom-right 2x2 of 4x4
# m = np.arange(16).reshape(4,4)
# arr11 = m[2:, 2:]
# print("11:\n", arr11)

# 12. Slice is a view
# v = np.array([1,2,3,4,5])
# s = v[:3]
# s[0] = 99
# print("12: v =", v, "| s =", s, "| v changed?", v[0] == 99)

# 13. Add 5 to ones((3,3))
# arr13 = np.ones((3,3)) + 5
# print("13:\n", arr13)

# 14. dot([1,2,3], [4,5,6])
# arr14 = np.dot([1,2,3], [4,5,6])
# print("14:", arr14)

# 15. mean of [1..10] as 2D row vector
# arr15 = np.mean(np.arange(1, 11).reshape(1, 10))
# print("15:", arr15)

# 16. Flatten 3x4 and reshape back
# m = np.arange(12).reshape(3,4)
# flat = m.flatten()
# back = flat.reshape(3,4)
# print("16: flat =", flat, "\n    back:\n", back)

# 17. squeeze (1,5,1) -> (5,)
# arr17 = np.squeeze(np.ones((1,5,1)))
# print("17: shape =", arr17.shape, "value =", arr17)

# 18. Transpose 2x3
# m18 = np.array([[1,2,3],[4,5,6]])
# print("18:\n", m18.T)

print("\n--- All assignment cells are ready ---")



--- All assignment cells are ready ---
