# Case Study - Cancer Prediction

Using the Wisconsin Breast Cancer dataset to compare multiple classification algorithms.

<hr>

## Import Libraries

In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import warnings
warnings.filterwarnings('ignore')

sns.set_style('whitegrid')

<hr>

## Load the Dataset

In [2]:
data = load_breast_cancer()
X = pd.DataFrame(data.data, columns=data.feature_names)
y = pd.Series(data.target, name='target')

print ('Dataset loaded successfully.\n')
print ('Number of samples: %s'%X.shape[0])
print ('Number of features: %s'%X.shape[1])
print ('Target classes: malignant (0), benign (1)')

Dataset loaded successfully.
Number of samples: 569
Number of features: 30
Target classes: malignant (0), benign (1)


<hr>

## Exploratory Data Analysis

In [3]:
print ('DataFrame shape: %s'%str(X.shape))
print ('\nTarget distribution:')
print (y.value_counts())
print ('\nFirst 5 rows of feature statistics:')
print (X.iloc[:, :5].describe())

DataFrame shape: (569, 30)

Target distribution:
0    212
1    357
Name: target, dtype: int64

First 5 rows of feature statistics:
       mean radius  mean texture  mean perimeter  mean area  mean smoothness
count   569.000000    569.000000      569.000000  569.00000       569.000000
mean     14.127292     19.289649       91.969033  654.88910         0.096360
std       3.524049      4.301036       24.298981  351.91408         0.014064
min       6.981000      9.710000       43.790000  143.50000         0.052630
25%      11.700000     16.170000       75.170000  420.30000         0.086370
50%      13.370000     18.840000       86.240000  551.10000         0.095870
75%      15.780000     21.500000      104.100000  782.70000         0.105300
max      28.110000     39.280000      188.500000  2501.00000         0.163400


In [4]:
print ('Missing values in dataset:')
print (X.isnull().sum())

Missing values in dataset:
mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
                           ..
worst symmetry             0
worst fractal dimension    0
Length: 30, dtype: int64


<hr>

## Train-Test Split

In [5]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print ('Training set: %s samples'%X_train.shape[0])
print ('Test set: %s samples'%X_test.shape[0])

Training set: 455 samples
Test set: 114 samples


<hr>

## Feature Scaling

Standardize features for Logistic Regression and SVM.

In [6]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print ('Features scaled using StandardScaler.')

Features scaled using StandardScaler.


<hr>

## Model 1: Logistic Regression

In [7]:
lr = LogisticRegression(random_state=42)
lr.fit(X_train_scaled, y_train)
y_pred_lr = lr.predict(X_test_scaled)

print ('--- Logistic Regression ---')
lr_acc = accuracy_score(y_test, y_pred_lr)
print ('Accuracy: %.4f\n'%lr_acc)
print ('Confusion Matrix:')
print (confusion_matrix(y_test, y_pred_lr))
print ('\nClassification Report:')
print (classification_report(y_test, y_pred_lr, target_names=data.target_names))

--- Logistic Regression ---
Accuracy: 0.9737

Confusion Matrix:
[[39  3]
 [ 0 72]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.93      0.96        42
           1       0.96      1.00      0.98        72

    accuracy                           0.97       114
   macro avg       0.98      0.96      0.97       114
weighted avg       0.97      0.97      0.97       114



<hr>

## Model 2: Random Forest Classifier

In [8]:
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)

print ('--- Random Forest Classifier ---')
rf_acc = accuracy_score(y_test, y_pred_rf)
print ('Accuracy: %.4f\n'%rf_acc)
print ('Confusion Matrix:')
print (confusion_matrix(y_test, y_pred_rf))
print ('\nClassification Report:')
print (classification_report(y_test, y_pred_rf, target_names=data.target_names))

--- Random Forest Classifier ---
Accuracy: 0.9561

Confusion Matrix:
[[39  3]
 [ 2 70]]

Classification Report:
              precision    recall  f1-score   support

           0       0.95      0.93      0.94        42
           1       0.96      0.97      0.97        72

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114



<hr>

## Model 3: Support Vector Classifier (SVC)

In [9]:
svc = SVC(kernel='rbf', random_state=42)
svc.fit(X_train_scaled, y_train)
y_pred_svc = svc.predict(X_test_scaled)

print ('--- Support Vector Classifier ---')
svc_acc = accuracy_score(y_test, y_pred_svc)
print ('Accuracy: %.4f\n'%svc_acc)
print ('Confusion Matrix:')
print (confusion_matrix(y_test, y_pred_svc))
print ('\nClassification Report:')
print (classification_report(y_test, y_pred_svc, target_names=data.target_names))

--- Support Vector Classifier ---
Accuracy: 0.9825

Confusion Matrix:
[[41  1]
 [ 1 71]]

Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.98      0.98        42
           1       0.99      0.99      0.99        72

    accuracy                           0.98       114
   macro avg       0.98      0.98      0.98       114
weighted avg       0.98      0.98      0.98       114



<hr>

## Model Comparison

In [10]:
print ('=== Model Comparison ===\n')
print ('Logistic Regression    : %.4f'%lr_acc)
print ('Random Forest          : %.4f'%rf_acc)
print ('SVC                    : %.4f'%svc_acc)
print ('\nBest model: SVC with accuracy %.4f'%max(lr_acc, rf_acc, svc_acc))

=== Model Comparison ===

Logistic Regression    : 0.9737
Random Forest          : 0.9561
SVC                    : 0.9825

Best model: SVC with accuracy 0.9825
