# Case Study: Handwritten Digit Recognition
<hr>
**Objective**: Recognize handwritten digits (0-9) using the **scikit-learn digits dataset**.

Comparing **Random Forest** and **SVC** classifiers on 8x8 pixel images.


In [1]:
import numpy as np, matplotlib.pyplot as plt
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
%matplotlib inline


In [2]:
digits = load_digits()
X, y = digits.data, digits.target
print("Dataset shape: %s\n" % str(X.shape))
print("Number of classes: %d\n" % len(np.unique(y)))
print("Class distribution:\n")
for i in range(10):
    print("  Digit %d: %d samples" % (i, np.sum(y==i)))


Dataset shape: (1797, 64)

Number of classes: 10

Class distribution:

  Digit 0: 178 samples
  Digit 1: 182 samples
  Digit 2: 177 samples
  Digit 3: 183 samples
  Digit 4: 181 samples
  Digit 5: 182 samples
  Digit 6: 181 samples
  Digit 7: 179 samples
  Digit 8: 174 samples
  Digit 9: 180 samples


In [3]:
fig, axes = plt.subplots(2, 5, figsize=(10,5))
for i, ax in enumerate(axes.flat):
    ax.imshow(digits.images[i], cmap="gray")
    ax.set_title("Digit: %d" % digits.target[i])
    ax.axis("off")
plt.tight_layout()
plt.show()


<hr>
**Data Preprocessing**

Split data and standardize pixel values.


In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
print("Train: %d, Test: %d\n" % (len(X_train), len(X_test)))


Train: 1257, Test: 540


<hr>
**Random Forest Classifier**


In [5]:
rf = RandomForestClassifier(n_estimators=200, random_state=42)
rf.fit(X_train_scaled, y_train)
y_pred_rf = rf.predict(X_test_scaled)
acc_rf = accuracy_score(y_test, y_pred_rf)
print("Random Forest Accuracy: %.4f\n" % acc_rf)
print("Confusion Matrix:\n%s\n" % confusion_matrix(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))


Random Forest Accuracy: 0.9778

Confusion Matrix:
[[53  0  0  0  0  0  0  0  0  0]
 [ 0 51  1  0  0  0  0  0  0  0]
 [ 0  0 51  0  0  0  0  0  0  0]
 [ 0  0  0 58  0  0  0  0  0  0]
 [ 0  0  0  0 52  0  0  0  0  0]
 [ 0  0  0  0  0 59  0  0  1  0]
 [ 0  0  0  0  0  0 54  0  0  0]
 [ 0  0  0  0  0  0  0 55  0  1]
 [ 0  1  0  0  0  0  0  0 48  0]
 [ 0  0  0  0  0  0  0  0  0 55]]

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        53
           1       0.98      0.98      0.98        52
           2       0.98      1.00      0.99        51
           3       1.00      1.00      1.00        58
           4       1.00      1.00      1.00        52
           5       1.00      0.98      0.99        60
           6       1.00      1.00      1.00        54
           7       1.00      0.98      0.99        56
           8       0.98      0.98      0.98        49
           9       0.98      1.00      0.99        55

    accuracy          

<hr>
**Support Vector Classifier (SVC)**


In [6]:
svc = SVC(kernel="rbf", gamma="scale", random_state=42)
svc.fit(X_train_scaled, y_train)
y_pred_svc = svc.predict(X_test_scaled)
acc_svc = accuracy_score(y_test, y_pred_svc)
print("SVC Accuracy: %.4f\n" % acc_svc)
print("Confusion Matrix:\n%s\n" % confusion_matrix(y_test, y_pred_svc))
print(classification_report(y_test, y_pred_svc))


SVC Accuracy: 0.9907

Confusion Matrix:
[[53  0  0  0  0  0  0  0  0  0]
 [ 0 52  0  0  0  0  0  0  0  0]
 [ 0  0 51  0  0  0  0  0  0  0]
 [ 0  0  0 58  0  0  0  0  0  0]
 [ 0  0  0  0 52  0  0  0  0  0]
 [ 0  0  0  0  0 59  0  0  1  0]
 [ 0  0  0  0  0  0 54  0  0  0]
 [ 0  0  0  0  0  0  0 55  0  1]
 [ 0  0  0  0  0  0  0  0 49  0]
 [ 0  0  0  0  0  0  0  0  0 55]]

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        53
           1       1.00      1.00      1.00        52
           2       1.00      1.00      1.00        51
           3       1.00      1.00      1.00        58
           4       1.00      1.00      1.00        52
           5       1.00      0.98      0.99        60
           6       1.00      1.00      1.00        54
           7       1.00      0.98      0.99        56
           8       0.98      1.00      0.99        49
           9       0.98      1.00      0.99        55

    accuracy                    

<hr>
**Confusion Matrix Visualization**


In [7]:
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14,6))

cm_rf = confusion_matrix(y_test, y_pred_rf)
im1 = ax1.imshow(cm_rf, interpolation="nearest", cmap=plt.cm.Blues)
ax1.set_title("Random Forest Confusion Matrix")
ax1.set_xlabel("Predicted")
ax1.set_ylabel("True")
plt.colorbar(im1, ax=ax1)

cm_svc = confusion_matrix(y_test, y_pred_svc)
im2 = ax2.imshow(cm_svc, interpolation="nearest", cmap=plt.cm.Greens)
ax2.set_title("SVC Confusion Matrix")
ax2.set_xlabel("Predicted")
ax2.set_ylabel("True")
plt.colorbar(im2, ax=ax2)

plt.tight_layout()
plt.show()


<hr>
**Sample Predictions**


In [8]:
n_samples = 10
sample_idx = np.random.choice(len(X_test_scaled), n_samples, replace=False)
fig, axes = plt.subplots(2, 5, figsize=(12,6))
for i, idx in enumerate(sample_idx):
    ax = axes.flat[i]
    ax.imshow(X_test[idx].reshape(8,8), cmap="gray")
    ax.set_title("True: %d, RF: %d, SVC: %d" % (y_test[idx], y_pred_rf[idx], y_pred_svc[idx]))
    ax.axis("off")
plt.tight_layout()
plt.show()


In [9]:
print("**Model Comparison:**\n")
print("Random Forest Accuracy: %.4f" % acc_rf)
print("SVC Accuracy:          %.4f" % acc_svc)
print("\nBoth models achieve excellent accuracy on digit recognition.")


**Model Comparison:**

Random Forest Accuracy: 0.9778
SVC Accuracy:          0.9907

Both models achieve excellent accuracy on digit recognition.
