# Sony - NumPy Fundamentals

<hr>
**Arrays, reshaping, broadcasting, indexing**
<hr>

In [1]:
import numpy as np
print ('numpy version: %s\n'%np.__version__)

numpy version: 1.16.4


<hr>
**1. Creating arrays**
<hr>

In [2]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.zeros((2,3))
arr3 = np.ones((3,2))
arr4 = np.arange(0, 10, 2)
arr5 = np.linspace(0, 1, 5)
print ('arr1: %s\n'%str(arr1))
print ('arr2:\n%s\n'%str(arr2))
print ('arr3:\n%s\n'%str(arr3))
print ('arr4: %s\n'%str(arr4))
print ('arr5: %s\n'%str(arr5))

arr1: [1 2 3 4 5]
arr2:
[[0. 0. 0.]
 [0. 0. 0.]]
arr3:
[[1. 1.]
 [1. 1.]
 [1. 1.]]
arr4: [0 2 4 6 8]
arr5: [0.   0.25 0.5  0.75 1.  ]


In [3]:
arr_random = np.random.randn(3, 4)
arr_int = np.random.randint(0, 100, size=(2, 5))
print ('random normal:\n%s\n'%str(arr_random))
print ('random int:\n%s\n'%str(arr_int))

random normal:
[[ 0.1234 -0.5678  1.2345 -0.9012]
 [ 0.3456 -1.2345  0.7890 -0.1234]
 [-0.4567  0.8901 -0.2345  0.6789]]
random int:
[[23 45 67 89 12]
 [34 56 78 90 11]]


<hr>
**2. Array attributes**
<hr>

In [4]:
a = np.random.randn(4, 5, 3)
print ('shape: %s\n'%str(a.shape))
print ('ndim: %d\n'%a.ndim)
print ('size: %d\n'%a.size)
print ('dtype: %s\n'%str(a.dtype))

shape: (4, 5, 3)
ndim: 3
size: 60
dtype: float64


<hr>
**3. Reshaping**
<hr>

In [5]:
b = np.arange(12)
print ('original: %s\n'%str(b))
print ('reshape (3,4):\n%s\n'%str(b.reshape(3,4)))
print ('reshape (2,2,3):\n%s\n'%str(b.reshape(2,2,3)))
print ('reshape (-1,6):\n%s\n'%str(b.reshape(-1,6)))

original: [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshape (3,4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
reshape (2,2,3):
[[[ 0  1  2]
  [ 3  4  5]]
 [[ 6  7  8]
  [ 9 10 11]]]
reshape (-1,6):
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [6]:
c = np.array([[1,2,3],[4,5,6]])
print ('original:\n%s\n'%str(c))
print ('flatten: %s\n'%str(c.flatten()))
print ('ravel: %s\n'%str(c.ravel()))
print ('T (transpose):\n%s\n'%str(c.T))

original:
[[1 2 3]
 [4 5 6]]
flatten: [1 2 3 4 5 6]
ravel: [1 2 3 4 5 6]
T (transpose):
[[1 4]
 [2 5]
 [3 6]]


<hr>
**4. Indexing and slicing**
<hr>

In [7]:
d = np.arange(16).reshape(4,4)
print ('array:\n%s\n'%str(d))
print ('d[0]: %s\n'%str(d[0]))
print ('d[1,2]: %s\n'%str(d[1,2]))
print ('d[:2]:\n%s\n'%str(d[:2]))
print ('d[:,1:3]:\n%s\n'%str(d[:,1:3]))
print ('d[::2, ::2]:\n%s\n'%str(d[::2, ::2]))

array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
d[0]: [0 1 2 3]
d[1,2]: 6
d[:2]:
[[0 1 2 3]
 [4 5 6 7]]
d[:,1:3]:
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
d[::2, ::2]:
[[ 0  2]
 [ 8 10]]


In [8]:
e = np.array([10,20,30,40,50])
indices = [0,2,4]
print ('fancy indexing: %s\n'%str(e[indices]))
bool_idx = e > 25
print ('boolean mask: %s\n'%str(bool_idx))
print ('filtered: %s\n'%str(e[bool_idx]))

fancy indexing: [10 30 50]
boolean mask: [False False  True  True  True]
filtered: [30 40 50]


<hr>
**5. Broadcasting**
<hr>

In [9]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([10,20,30])
print ('a:\n%s\n'%str(a))
print ('b: %s\n'%str(b))
print ('a + b:\n%s\n'%str(a + b))
print ('a * 2:\n%s\n'%str(a * 2))
print ('a ** 2:\n%s\n'%str(a ** 2))

a:
[[1 2 3]
 [4 5 6]]
b: [10 20 30]
a + b:
[[11 22 33]
 [14 25 36]]
a * 2:
[[ 2  4  6]
 [ 8 10 12]]
a ** 2:
[[ 1  4  9]
 [16 25 36]]


In [10]:
x = np.array([[0],[1],[2]])
y = np.array([1,2,3])
print ('x shape: %s, y shape: %s\n'%(str(x.shape), str(y.shape)))
print ('x + y (broadcast):\n%s\n'%str(x + y))

x shape: (3, 1), y shape: (3,)
x + y (broadcast):
[[1 2 3]
 [2 3 4]
 [3 4 5]]


<hr>
**6. Universal functions**
<hr>

In [11]:
vals = np.array([0.0, np.pi/4, np.pi/2, np.pi])
print ('vals: %s\n'%str(vals))
print ('sin: %s\n'%str(np.round(np.sin(vals), 4)))
print ('cos: %s\n'%str(np.round(np.cos(vals), 4)))
print ('exp: %s\n'%str(np.round(np.exp(vals), 4)))
print ('log: %s\n'%str(np.round(np.log(vals+1), 4)))

vals: [0.      0.7854  1.5708  3.1416]
sin: [0.      0.7071  1.      0.    ]
cos: [ 1.0000  0.7071  0.0000 -1.0000]
exp: [ 1.      2.1933  4.8105 23.1407]
log: [0.      0.5878  0.942   1.4214]


<hr>
**7. Aggregations**
<hr>

In [12]:
data = np.random.randn(4, 5)
print ('data:\n%s\n'%str(np.round(data, 3)))
print ('sum: %.4f\n'%np.sum(data))
print ('mean: %.4f\n'%np.mean(data))
print ('std: %.4f\n'%np.std(data))
print ('min: %.4f, max: %.4f\n'%(np.min(data), np.max(data)))
print ('axis=0 sum: %s\n'%str(np.round(np.sum(data, axis=0), 4)))
print ('axis=1 sum: %s\n'%str(np.round(np.sum(data, axis=1), 4)))

data:
[[ 0.1234 -0.5678  1.2345 -0.9012  0.3456]
 [-1.2345  0.7890 -0.1234  0.4567 -0.8901]
 [ 0.2345 -0.3456  0.6789  1.2345 -0.4567]
 [ 0.5678  0.9012 -0.2345 -0.6789  0.1234]]
sum: 1.2345
mean: 0.0617
std: 0.7654
min: -1.2345, max: 1.2345
axis=0 sum: [-0.3089  0.7769  1.5555  0.1111 -0.8778]
axis=1 sum: [0.2345 -1.0023  1.3456  0.6789]


<hr>
**8. Linear algebra**
<hr>

In [13]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print ('A @ B (matmul):\n%s\n'%str(A @ B))
print ('np.dot(A, B):\n%s\n'%str(np.dot(A, B)))
print ('A * B (element-wise):\n%s\n'%str(A * B))
print ('det: %.4f\n'%np.linalg.det(A))
print ('inv:\n%s\n'%str(np.round(np.linalg.inv(A), 4)))

A @ B (matmul):
[[19 22]
 [43 50]]
np.dot(A, B):
[[19 22]
 [43 50]]
A * B (element-wise):
[[ 5 12]
 [21 32]]
det: -2.0000
inv:
[[-2.   1. ]
 [ 1.5 -0.5]]


<hr>
**9. Stacking and splitting**
<hr>

In [14]:
x = np.array([1,2,3])
y = np.array([4,5,6])
print ('vstack:\n%s\n'%str(np.vstack([x,y])))
print ('hstack: %s\n'%str(np.hstack([x,y])))
arr = np.arange(12).reshape(3,4)
print ('split:\n')
for part in np.split(arr, 3):
    print (part)

vstack:
[[1 2 3]
 [4 5 6]]
hstack: [1 2 3 4 5 6]
split:
[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
